---
- hosts: all
  become: yes
  tasks:
    - name: Ensure NTP is installed.
      apt: name=ntp state=present

    - name: Ensure NTP is running.
      service: name=ntp state=started enabled=yes

    - name: Install desktop needed for emulation station
      command:
        cmd: tasksel install desktop gnome-desktop

    - name: Check sudo group
      group: name=pi state=present

    - name: Allow 'pi' group to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^%pi'
        line: '%pi ALL=(ALL) NOPASSWD: ALL'
        validate: visudo -cf %s

    - name: Add pi user and add it to sudo
      user:
        name: pi
        groups: pi
        append: yes
        createhome: yes
        state: present

    - name: Set authorized key for user ubuntu copying it from current user
      authorized_key:
        user: pi
        state: present
        key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
